### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by MengruiLIU** [shaido987/multi-dim-baselines#8]
Hi, I have a question about the input data, how is the data input to the different algorithms?  Thanks a lot in advance

**Comment by shaido987** [comment]
Hello, thanks for your interest.

You can run the different algorithms using single files or a whole directory with files. For a single file, you can use for example:
```
python run.py riskloc --run-path /data/B0/B_cuboid_layer_1_n_ele_1/1450653900.csv --debug
```
Where the file is `/data/B0/B_cuboid_layer_1_n_ele_1/1450653900.csv` (instructions for obtaining the files can be seen here: https://github.com/shaido987/riskloc#datasets).

This will run the [`run_instance`](https://github.com/shaido987/riskloc/blob/main/run.py#L51) method in `run.py` which loads the data using [`read_dataframe`](https://github.com/shaido987/riskloc/blob/09f35cf68512376353da82254c12c7da6f726b95/utils/run_utils.py#L55) in utils/run_utils.py. After obtaining a pandas dataframe with the data, the [`run_method`](https://github.com/shaido987/riskloc/blob/09f35cf68512376353da82254c12c7da6f726b95/utils/run_utils.py#L12) method (also in utils/run_utils.py) is called with the data and the algorithm name. This method is responsible for calling the correct algorithm with the input data. This is essentially an if-else statement that checks which algorithm name the `run` function was called with:

https://github.com/shaido987/riskloc/blob/09f35cf68512376353da82254c12c7da6f726b95/utils/run_utils.py#L12-L52

**Comment by MengruiLIU** [comment]
Thanks for the patient explanation, is the data used here the same data for squeeze paper? I should download it from the Tsinghua university cloud, then put it in the "data " folder

**Comment by shaido987** [comment]
Yes, I used their data together with 3 synthetic datasets. You can download it from the Tsinghua cloud and put them in folders `/data/A/`, `/data/B0/`, `/data/B1/`, ..., `/data/D/`. Then you should be able to run with the commands under "How to run" in the readme.

**Comment by MengruiLIU** [comment]
Hi, Thanks for your answer, but I run into a problem, the error shows 
ArgumentTypeError: data-root (./data) must be prefix of run-path (/data/B0/B_cuboid_layer_1_n_ele_1/1450653900.csv).
should I change the run-path?

**Comment by MengruiLIU** [comment]
I have successed run the script with your help, thanks very much. 

I still have few question about the result, 

1.Is the predicted labels show the root cause for each data sheet?
2. In the dataset, is the Real and Predict indicated the existence counting number of different attribute combination in the dataset? like if one combination is only existing once, then the real is 1
3. Is the TP, FP, FN and F1 show the rate of Real and Anomaly combination number? when the predict is different with the real, it considers as anomaly?

Thanks in advance

**Comment by shaido987** [comment]
Happy to help. 

1. The true root causes for the samples are in the injection_info files. For example, `B0\B_cuboid_layer_1_n_ele_1\injection_info.csv` contains all root causes of the samples in the `B0\B_cuboid_layer_1_n_ele_1` folder. The algorithms will all make different predictions of the root cause (the predicted labels) which may differ from the true root cause (in the file).
2. Not exactly. Each attribute combination is unique so there is only a single one of each in a dataset sample. But each attribute combination is associated with an *actual value* and a *forecasted value*. The actual value comes from the data, for example, if the time series measure is the number of people using a service and the attributes are (country, city, datacenter) then one possible attribute combination could be (Country=China, City=Beijing, DataCenter=X). The *actual value* of this attribute combination is then the true number of people that used the service during the period that was abnormal (where you want to identify the root cause). The forecasted value is the predicted number of people using the service under the same period (i.e., what is a normal usage if no anomaly occurred).
3. These are a way of evaluating the effectiveness of the different algorithms. TP, FP, FN, and F1 are "True Positive", "False Positive", "False Negative", and F1-score: see https://en.wikipedia.org/wiki/F-score for an explanation of all terms. In essence, if an algorithm makes a root cause prediction with elements not in the true root cause set then it counts as False Positives. If the algorithm missed predicting elements that are in the true root cause set then these count as False Negatives. True Positives are the number of elements that an algorithm predicts and are in the true root cause set (so any successful predictions). The F1-score is a way to take these numbers and combine them into a single value. A high F1-score corresponds to an accurate algorthim that misses few root causes and gives few incorrect ones.

The paper linked in the readme file gives some more details on the evaluation and more formal definitions for the different components of the problem. Also, consider giving a star to this repository if you found it useful~

**Comment by MengruiLIU** [comment]
Very helpful information, now I understand the datasheet, thanks a lot.
And I try to use other data to achieve the algorithm hotspot, but It keeps giving me the Error like the following,
File "C:\Users\usrlocal\run.py", line 108, in <module>
    run_directory(data_root, run_path, args.algorithm, algorithm_args, args.derived, args.n_threads, csv_suffix,
  File "C:\Users\usrlocal\run.py", line 33, in run_directory
    result_post_processing(parallel_run_results, algorithm, csv_suffix)
  File "C:\Users\usrlocal\utils\run_utils.py", line 124, in result_post_processing
    df.columns = ['Dataset', 'Folder', 'File', 'F1', 'TP', 'FP', 'FN', 'Time']
  File "C:\Users\usrlocal\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 5920, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\usrlocal\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 822, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\usrlocal\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\internals\managers.py", line 228, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Users\usrlocal\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\internals\base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 8 elements

Do you happen to know the possible reason?
Best regards

**Comment by shaido987** [comment]
It appears that there is some problem when running the algorithm so the result is empty. 

Try to run a single file first to make sure it works (running a whole folder with files uses asyncronized multiprocessing so it won't return the correct errors). You can try the following code, but you may need to adjust the path (just make sure it points to a single file):

```
python run.py hotspot --run-path data/B0/B_cuboid_layer_1_n_ele_1/1450653900.csv
```

**Comment by MengruiLIU** [comment]
Hi Shaido987
Thanks for your help. I have found the problem like below.
Layer: 1
Cuboid: ['Temperature']
Best subset: [(0.263979429,)] score 0.9579382897007255
Traceback (most recent call last):
  File "C:\Users\usrlocal\run.py", line 101, in <module>
    run_single_file(data_root, run_path, args.algorithm, algorithm_args, args.derived)
  File "C:\Users\usrlocal\run.py", line 48, in run_single_file
    run_instance(data_root, dataset_name, sub_directory, file, algorithm, algorithm_args, derived, debug=True)
  File "C:\Users\usrlocal\run.py", line 73, in run_instance
    root_cause_predictions = root_cause_postprocessing(root_causes, algorithm)
  File "C:\Users\usrlocal\utils\evaluation.py", line 49, in root_cause_postprocessing
    elems = np.array([d + '=' for d in rc['cuboid']], dtype=object) + np.array(rc['elements'], dtype=object)
TypeError: can only concatenate str (not "float") to str

It seems the data type problem, perhaps because that I change the attribute parameters to number, such as Beijing to 0.11122. 

But I don't really know how to solve the problem, if it is the data type problem, the algorithm is still can working on the layer 1, and I tried to use the hostspot algorithm, I think it should not go to the squeeze algorithm here, elems = np.array([d + '=' for d in rc['cuboid']], dtype=object) + np.array(rc['elements'], dtype=object).  Thanks for your help in advance.

**Comment by shaido987** [comment]
Hello @MengruiLIU 

Yes, the cuboid and dimension names were assumed to both be strings. I added an update of the code where it crashed to correctly cast everything to strings. I think it should be working now with the update, please try it again with the updated code.

If it still throws some error you can try with string names or send me the new error here and I can investigate it.
